//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLIENT_MANAGEMENTEntities : DbContext
    {
        public CLIENT_MANAGEMENTEntities()
            : base("name=CLIENT_MANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENT> CLIENT { get; set; }
        public DbSet<TASK> TASK { get; set; }
        public DbSet<USER> USER { get; set; }
        public DbSet<USER_TYPE> USER_TYPE { get; set; }
    }
}
